[project]
name = "semantic-network-formation-sheaves"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gdown>=5.2.0",
    "hydra-core>=1.3.2",
    "igraph>=0.11.8",
    "numpy>=2.2.5",
    "python-dotenv>=1.1.0",
    "pytorch-lightning>=2.5.1.post0",
    "scikit-learn>=1.6.1",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
    "wandb>=0.19.10",
]

[tool.ruff]
target-version = "py310"
line-length = 79

[tool.ruff.lint]
extend-select = [
        "C4",
        "SIM",
        "UP",
        "TCH",
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
